### PR TITLE
cleanup no longer working/needed fixes

### PR DESCRIPTION
**Pull request by soredake**

### CODE REVIEW

**Comment by mrjackv** [comment]
This PR is quite interesting as it raises an issue that @simons-public has not yet addressed regarding backwards-compatibility of fixes. While it does make sense to always be consistent with the latest version I still think that some degree of compatibility with older version of protons might be beneficial (e.g. in case of regressions). IMHO supporting the last 3 releases (currently 5.0, 4.11 and 4.2) might be the right balance. Maybe something like a decorator (somthing like `@DeprecatedSince(1544476838)` or `@DeprecatedSince("4.2-2")` ) applied to the `main()` function would do the trick.

That said I've looked at the changes and it is true that some fixes, especially those corefonts-related and games that have been whitelisted in the meantime should be dropped (it has been 2 years since the inclusion of corefonts in proton). However I compared the fixes with protondb and the proton issue threads (as I do not own most of them) and found some irregularities:

* Serious Sam Double D XXL (111600) does launch successfully and play well with proton-mono, however while loading a save it would consistently crash (tested as I have the game)
* Fallout New Vegas (22380): recent protondb reports seem to suggest that the installation of additional libraries is no longer needed, however it might be nice to keep the config fixed if relevant and add the virtual desktop fix for alt-tabbing
* Styx (242640): depending on the first paragraph discussion this might be temporarely kept with the `util.set_environment("PROTON_USE_D9VK", "1")` for proton 4.x
* Banished (242920): same as styx, might be nice to have the override built-in
* Batman Arkham Asylum (35140): both the protondb reports and proton issues indicate that it still needs the external libraries to work
* Portal Knights (374040): similar to to fallout, it might be nice to have the config fixed by protonfixes

**Comment by mrjackv** [comment]
This PR is quite interesting as it raises an issue that @simons-public has not yet addressed regarding backwards-compatibility of fixes. While it does make sense to always be consistent with the latest version I still think that some degree of compatibility with older version of protons might be beneficial (e.g. in case of regressions). IMHO supporting the last 3 releases (currently 5.0, 4.11 and 4.2) might be the right balance. Maybe something like a decorator (somthing like `@DeprecatedSince(1544476838)` or `@DeprecatedSince("4.2-2")` ) applied to the `main()` function would do the trick.

That said I've looked at the changes and it is true that some fixes, especially those corefonts-related and games that have been whitelisted in the meantime should be dropped (it has been 2 years since the inclusion of corefonts in proton). However I compared the fixes with protondb and the proton issue threads (as I do not own most of them) and found some irregularities:

* Serious Sam Double D XXL (111600) does launch successfully and play well with proton-mono, however while loading a save it would consistently crash (tested as I have the game)
* Fallout New Vegas (22380): recent protondb reports seem to suggest that the installation of additional libraries is no longer needed, however it might be nice to keep the config fixed if relevant and add the virtual desktop fix for alt-tabbing
* Styx (242640): depending on the first paragraph discussion this might be temporarely kept with the `util.set_environment("PROTON_USE_D9VK", "1")` for proton 4.x
* Banished (242920): same as styx, might be nice to have the override built-in
* Batman Arkham Asylum (35140): both the protondb reports and proton issues indicate that it still needs the external libraries to work
* Portal Knights (374040): similar to to fallout, it might be nice to have the config fixed by protonfixes

**Comment by simons-public** [comment]
@mrjackv backwards compatibility is a problem I'd been putting off addressing, but I merged your pull request with the '@DeprecatedSince' decorator. Up until now I hadn't seen any fixes that cause issues when they are no longer required, but I assume thats a possibility and it clearly slows things down to install unnecessary winetricks. 

@soredake Since mrjackv's changes have been merged, if you want to resubmit with the `@DeprecatedSince` decorator on `main` for the games not mentioned above I'd be happy to merge.

Unfortunately for games I don't have I've been relying entirely on pull requests/issues for info, so I appreciate the input. 

On a sidenote, I've keep the corefonts fix even after the proton implementation since they are using `liberation-fonts` which doesn't include all of the same fonts and may not have 100% coverage or compatibility.

**Comment by soredake** [comment]
Where i should put @DeprecatedSince?

**Comment by mrjackv** [comment]
You put it on top of the `main()` function
```
""" Example fix
"""

from protonfixes import util
from protonfixes.protonversion import DeprecatedSince

@DeprecatedSince("4.11-10")
def main():
  util.protontricks("corefonts")
```
You can also use timestamps (e.g. `@DeprecatedSince(1582148269)`), although imho you loose some readability

**Comment by soredake** [comment]
Updated.

**Pull request merged**
